-- schema.sql
-- Run this SQL in your Supabase project's SQL Editor to create the database tables.
-- Go to: Supabase Dashboard → Your Project → SQL Editor → Paste this → Run

-- ─────────────────────────────────────────
-- TABLE: shops
-- Stores all shop data collected during the interview
-- ─────────────────────────────────────────
CREATE TABLE IF NOT EXISTS shops (
    -- Unique identifier for each shop (UUID generated by the app)
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    -- Core shop identity
    shop_name TEXT,
    tagline TEXT,
    shop_type TEXT CHECK (shop_type IN ('food', 'clothing', 'services', 'general')),

    -- Products stored as a JSON array of strings: ["chai", "samosa", "jalebi"]
    products JSONB DEFAULT '[]'::jsonb,

    -- Business hours
    opening_time TEXT,
    closing_time TEXT,
    open_days TEXT,

    -- Contact & location
    location TEXT,
    phone TEXT,

    -- Extra info the owner mentioned
    extra_info TEXT,

    -- Generated website
    site_url TEXT,           -- The live Vercel URL, e.g. https://sharma-store.vercel.app
    site_html TEXT,          -- The full generated HTML (stored for re-publishing)

    -- Timestamps (stored in UTC)
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- ─────────────────────────────────────────
-- TABLE: site_views
-- Tracks how many times each shop's website was visited
-- (Optional — for future analytics feature)
-- ─────────────────────────────────────────
CREATE TABLE IF NOT EXISTS site_views (
    id BIGSERIAL PRIMARY KEY,
    shop_id UUID REFERENCES shops(id) ON DELETE CASCADE,
    viewed_at TIMESTAMPTZ DEFAULT NOW(),
    user_agent TEXT,         -- Browser info (to detect mobile vs desktop)
    referrer TEXT            -- Where the visitor came from (WhatsApp, Google, etc.)
);

-- ─────────────────────────────────────────
-- INDEXES (makes database queries faster)
-- ─────────────────────────────────────────

-- Find shops by their live URL quickly
CREATE INDEX IF NOT EXISTS idx_shops_site_url ON shops(site_url);

-- Find shops by phone number (for duplicate detection)
CREATE INDEX IF NOT EXISTS idx_shops_phone ON shops(phone);

-- Find shops by type (for analytics)
CREATE INDEX IF NOT EXISTS idx_shops_type ON shops(shop_type);

-- Find views for a specific shop
CREATE INDEX IF NOT EXISTS idx_views_shop_id ON site_views(shop_id);

-- ─────────────────────────────────────────
-- AUTO-UPDATE: updated_at timestamp
-- Automatically sets updated_at whenever a shop row is changed
-- ─────────────────────────────────────────
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER shops_updated_at
    BEFORE UPDATE ON shops
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- ─────────────────────────────────────────
-- ROW LEVEL SECURITY (RLS)
-- Makes your database safe — only your backend can write data
-- ─────────────────────────────────────────
ALTER TABLE shops ENABLE ROW LEVEL SECURITY;
ALTER TABLE site_views ENABLE ROW LEVEL SECURITY;

-- Allow anyone to read shops (needed to show the published website)
CREATE POLICY "Anyone can read shops"
    ON shops FOR SELECT
    USING (true);

-- Allow anyone to read site_views (for analytics)
CREATE POLICY "Anyone can read site_views"
    ON site_views FOR SELECT
    USING (true);

-- Only authenticated service role can insert/update/delete
-- (Your backend uses the service_role key, so this works fine)
CREATE POLICY "Service role can manage shops"
    ON shops FOR ALL
    USING (auth.role() = 'service_role');

CREATE POLICY "Service role can manage site_views"
    ON site_views FOR ALL
    USING (auth.role() = 'service_role');

-- ─────────────────────────────────────────
-- TABLE: product_photos
-- Stores uploaded product photos per shop
-- ─────────────────────────────────────────
CREATE TABLE IF NOT EXISTS product_photos (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    shop_id UUID REFERENCES shops(id) ON DELETE CASCADE,

    -- Photo info
    product_name TEXT NOT NULL,
    filename TEXT NOT NULL,           -- Stored filename on server
    image_url TEXT NOT NULL,          -- Public URL to access the photo
    enhanced BOOLEAN DEFAULT FALSE,   -- Whether AI enhancement was applied
    emoji TEXT DEFAULT '✨',           -- AI-suggested emoji for the product
    background_style TEXT DEFAULT 'white',  -- white / gradient / warm
    display_order INT DEFAULT 0,      -- For ordering cards on the website

    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_product_photos_shop_id ON product_photos(shop_id);

ALTER TABLE product_photos ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Anyone can read product_photos"
    ON product_photos FOR SELECT USING (true);

CREATE POLICY "Service role can manage product_photos"
    ON product_photos FOR ALL USING (auth.role() = 'service_role');


-- ─────────────────────────────────────────
INSERT INTO shops (
    shop_name, tagline, shop_type, products,
    opening_time, closing_time, open_days,
    location, phone, extra_info
) VALUES (
    'Sharma General Store',
    'Ghar ki zaroorat, ek hi jagah',
    'general',
    '["Atta", "Chawal", "Dal", "Tel", "Soap", "Shampoo"]'::jsonb,
    '8:00 AM', '10:00 PM', 'Monday to Sunday',
    'Sardarpura, Jodhpur',
    '9876543210',
    'Home delivery available within 2km'
);
